#!/usr/bin/env python3
"""Generate single-note probe songs for `make pitch-report`.

One probe per synth type. Each plays all 96 notes (C-0 .. B-7), one per row,
on channel 0 with the other channels silent. Probes are deliberately dull:
instant attack, full sustain, no release, no pitch envelope, no effects. A
note that moves cannot be measured for pitch, and a note that decays to
nothing takes its fundamental with it.

Row length is the one number that matters. At bpm=60 / ticks=12 a row is
12 * (44100*5 // 120) = 22044 samples, half a second, which is 8 cycles even
at C-0 (16.35 Hz) and ~2000 at B-7. That is ample for the phase-regression
estimator in pitch_report.mjs, which needs cycles rather than seconds.

KS is exempt from "no decay" — a pluck decays by construction — so it gets the
lowest damping available to keep the tail alive across the whole row.
"""

import os
import sys

NOTE_NAMES = ["C-", "C#", "D-", "D#", "E-", "F-", "F#", "G-", "G#", "A-", "A#", "B-"]

BPM = 60
TICKS = 12
ROWS_PER_PATTERN = 48          # 96 notes / 2 patterns, inside BIRB_MAX_ROWS=64
NUM_NOTES = 96

# Per-probe instrument line. Keep these sustained and unmodulated.
PROBES = {
    "pulse50": "@inst 0 pulse50 A:0 D:0 S:255 R:0 V:255",
    "tri":     "@inst 0 tri     A:0 D:0 S:255 R:0 V:255",
    "saw":     "@inst 0 saw     A:0 D:0 S:255 R:0 V:255",
    "sine":    "@inst 0 sine    A:0 D:0 S:255 R:0 V:255",
    "ks":      "@inst 0 ks      damping=0 A:0 D:0 S:255 R:0 V:255",
    "formant": "@inst 0 formant source=saw vowela=A vowelb=A sweep=0 "
               "resonance=128 adsr=0,0,255,0 volume=255",
    # FM takes the explicit A:/D:/S:/R: form — adsr=... alone leaves the
    # instrument envelope at 0,0,0,0 and the probe renders silence.
    "fm":      "@inst 0 fm      nops=2 algo=0 modidx=32 feedback=0 "
               "A:0 D:0 S:255 R:0 V:255",
}


def note_name(n):
    return "%s%d" % (NOTE_NAMES[n % 12], n // 12)


def build(name, inst_line):
    out = [
        "# %s pitch probe — generated by tools/gen_probes.py, do not edit" % name,
        "# One note per row, C-0 .. B-7, channel 0 only.",
        "",
        "@bpm %d" % BPM,
        "@ticks %d" % TICKS,
        "",
        inst_line,
        "",
        "@order",
    ]
    num_patterns = (NUM_NOTES + ROWS_PER_PATTERN - 1) // ROWS_PER_PATTERN
    for p in range(num_patterns):
        out.append("%d 0 0 0" % p)
    out.append("")

    for p in range(num_patterns):
        out.append("@pattern %d %d" % (p, ROWS_PER_PATTERN))
        for r in range(ROWS_PER_PATTERN):
            n = p * ROWS_PER_PATTERN + r
            cell = "%s 00 ---" % note_name(n) if n < NUM_NOTES else "--- -- ---"
            out.append("%s | --- -- --- | --- -- --- | --- -- ---" % cell)
        out.append("")
    return "\n".join(out) + "\n"


# ---- 4xy vibrato probe ----
# One row per depth y, same note throughout, so the only variable is depth.
# Slower tempo and more ticks per row than the pitch probes: the report has to
# see several LFO cycles inside a row to find the peak deviation, and the
# effect column's speed nibble only gets 64/x ticks per cycle.
VIB_BPM = 60
VIB_TICKS = 24
VIB_SPEED = 8          # high nibble of 4xy -> 8 ticks per LFO cycle
VIB_NOTE = "A-4"       # 440 Hz: high enough to pitch-track in short windows
VIB_ROWS = 16          # y = 0 (reference) .. 15


def build_vibrato():
    out = [
        "# 4xy vibrato probe — generated by tools/gen_probes.py, do not edit",
        "# Row y plays %s with effect 4%X%X. Row 0 is the no-vibrato reference."
        % (VIB_NOTE, VIB_SPEED, 0),
        "",
        "@bpm %d" % VIB_BPM,
        "@ticks %d" % VIB_TICKS,
        "",
        "@inst 0 sine A:0 D:0 S:255 R:0 V:255",
        "",
        "@order",
        "0 0 0 0",
        "",
        "@pattern 0 %d" % VIB_ROWS,
    ]
    for y in range(VIB_ROWS):
        fx = "---" if y == 0 else "4%X%X" % (VIB_SPEED, y)
        out.append("%s 00 %s | --- -- --- | --- -- --- | --- -- ---" % (VIB_NOTE, fx))
    out.append("")
    return "\n".join(out) + "\n"


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else "build/probes"
    os.makedirs(outdir, exist_ok=True)
    for name, inst in PROBES.items():
        path = os.path.join(outdir, "probe_%s.birb" % name)
        with open(path, "w") as f:
            f.write(build(name, inst))
        print("wrote %s" % path)
    with open(os.path.join(outdir, "probe_vibrato.birb"), "w") as f:
        f.write(build_vibrato())
    print("wrote %s/probe_vibrato.birb" % outdir)

    # The report needs these to segment the render; keep them in one place.
    with open(os.path.join(outdir, "probes.json"), "w") as f:
        f.write('{"bpm": %d, "ticks": %d, "rows_per_pattern": %d, '
                '"num_notes": %d, "probes": [%s],\n'
                ' "vibrato": {"bpm": %d, "ticks": %d, "rows": %d, "note": %d, '
                '"speed": %d}}\n'
                % (BPM, TICKS, ROWS_PER_PATTERN, NUM_NOTES,
                   ", ".join('"%s"' % k for k in PROBES),
                   VIB_BPM, VIB_TICKS, VIB_ROWS,
                   4 * 12 + 9,   # A-4 as a note index
                   VIB_SPEED))


if __name__ == "__main__":
    main()
